# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-21 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cycle_start', models.DateField()),
                ('cycle_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('billed', 'billed'), ('grace', 'grace')], max_length=6)),
                ('status_change', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semitki_manager.PaymentGateway'),
        ),
        migrations.AddField(
            model_name='bill',
            name='billing_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semitki_manager.BillingAccount'),
        ),
    ]
