# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semitki_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('billing_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semitki_manager.BillingAccount')),
            ],
        ),
    ]
