# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bucket',
            new_name='data',
        ),
    ]
