# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0004_auto_20170202_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.AccountsGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='group_id',
        ),
        migrations.AddField(
            model_name='useraccountsgroup',
            name='user_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.UserAccount'),
        ),
    ]
