# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0005_auto_20170202_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupedSocialAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='AccountsGroup',
            new_name='SocialAccount',
        ),
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='SocialAccountsGroup',
        ),
        migrations.RemoveField(
            model_name='useraccountsgroup',
            name='account_group_id',
        ),
        migrations.RemoveField(
            model_name='useraccountsgroup',
            name='user_account_id',
        ),
        migrations.DeleteModel(
            name='UserAccountsGroup',
        ),
        migrations.AddField(
            model_name='groupedsocialaccounts',
            name='social_account_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.SocialAccountsGroup'),
        ),
        migrations.AddField(
            model_name='groupedsocialaccounts',
            name='social_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.SocialAccount'),
        ),
    ]
