# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0007_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('template', models.CharField(max_length=140)),
                ('page', models.CharField(max_length=100)),
            ],
        ),
    ]
