# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0008_staticpages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='campaing_id',
        ),
        migrations.AddField(
            model_name='topic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.Project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
