# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0010_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='description',
            new_name='bucket',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='id',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='access_token',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='email',
            field=models.CharField(default='algo', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='password',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=140, primary_key=True, serialize=False),
        ),
    ]
