# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0011_auto_20170318_0026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupedSocialAccounts',
            new_name='GroupedSocialAccount',
        ),
    ]
