# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0013_auto_20170329_1821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterField(
            model_name='socialaccountsgroup',
            name='socialaccounts',
            field=models.ManyToManyField(blank=True, to='sonetworks.SocialAccount'),
        ),
    ]
