# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0015_auto_20170330_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='page',
        ),
    ]
