# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0016_remove_staticpage_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('isactive', models.BooleanField(default=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('isactive', models.BooleanField(default=True)),
                ('validTo', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isactive', models.BooleanField(default=True)),
                ('validTo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=256)),
                ('isactive', models.BooleanField(default=True)),
                ('validTo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialaccountsgroup',
            name='socialaccounts',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='project',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='validTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='SocialAccountsGroup',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='socialaccountgroup',
            name='socialaccount',
            field=models.ManyToManyField(blank=True, to='sonetworks.SocialAccount'),
        ),
        migrations.AddField(
            model_name='socialaccountgroup',
            name='socialgroup',
            field=models.ManyToManyField(blank=True, to='sonetworks.SocialGroup'),
        ),
    ]
