# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0017_auto_20170410_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phase',
            field=models.ForeignKey(to='sonetworks.Phase'),
            preserve_default=False,
        ),
    ]
