# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0018_post_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase',
            old_name='validTo',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='validTo',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='socialaccountgroup',
            old_name='validTo',
            new_name='valid_to',
        ),
        migrations.RenameField(
            model_name='socialgroup',
            old_name='validTo',
            new_name='valid_to',
        ),
    ]
