# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0019_auto_20170410_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccountgroup',
            name='socialgroup',
        ),
        migrations.AddField(
            model_name='socialaccountgroup',
            name='socialgroup',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sonetworks.SocialGroup'),
            preserve_default=False,
        ),
    ]
