# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0020_auto_20170410_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='token_expiration',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
