# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0021_socialaccount_token_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='campaign',
        ),
        migrations.AddField(
            model_name='phase',
            name='campaign',
            field=models.ManyToManyField(to='sonetworks.Campaign'),
        ),
    ]
