# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0022_auto_20170412_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='campaign',
        ),
        migrations.AddField(
            model_name='phase',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='sonetworks.Campaign'),
            preserve_default=False,
        ),
    ]
