# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0026_auto_20170421_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccountgroup',
            name='social_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related', to='sonetworks.SocialGroup'),
        ),
    ]
