# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 02:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0027_auto_20170422_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
