# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0028_auto_20170509_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='bucket_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'img/'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
