# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0029_post_published'),
        ('sonetworks', '0029_auto_20170509_2122'),
    ]

    operations = [
    ]
