# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0033_auto_20170514_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='email',
            field=models.CharField(max_length=256),
        ),
    ]
