# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0036_post_publish_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_id',
        ),
    ]
