# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonetworks', '0037_auto_20170519_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestoken',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
