# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0039_auto_20170520_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestoken',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'img/'),
        ),
        migrations.AddField(
            model_name='pagestoken',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
