# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('sonetworks', '0040_auto_20170520_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestoken',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialToken'),
            preserve_default=False,
        ),
    ]
