# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:47
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonetworks', '0043_auto_20170522_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourRelated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('show', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TourView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tourrelated',
            name='tourview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.TourView'),
        ),
        migrations.AddField(
            model_name='tourelement',
            name='tourview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sonetworks.TourView'),
        ),
    ]
