# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0044_auto_20170621_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourelement',
            old_name='attributes',
            new_name='options',
        ),
    ]
