# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonetworks', '0045_auto_20170621_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[(b'image', b'image'), (b'video', b'video')], max_length=5)),
                ('file_extension', models.CharField(max_length=4)),
                ('file_url', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
