# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0046_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownSharingService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=255)),
                ('api_url', models.CharField(max_length=255)),
                ('hosting_type', models.CharField(choices=[(b'any', b'any'), (b'image', b'image'), (b'video', b'video')], max_length=5)),
            ],
        ),
    ]
