# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sonetworks', '0048_posterror'),
    ]

    operations = [
        migrations.AddField(
            model_name='posterror',
            name='post',
            field=models.ForeignKey(default='89f88419-0fed-4c1b-9c44-b6cac52e9588', on_delete=django.db.models.deletion.CASCADE, related_name='post_error', to='sonetworks.Post'),
            preserve_default=False,
        ),
    ]
